/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.editSubject;

import controller.Process;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import model.Subject;
import view.EditSubjects;
/**
 *
 * @author 19
 */
public class EditSubjectDetails extends javax.swing.JFrame {
    private static Subject selectedSubject;
    /**
     * Creates new form EditSubjectDetails
     */
    public EditSubjectDetails() {
        
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/edit_subject_small.png")));
        
        selectedSubject = Process.subjects.get(EditSubjects.selectedSubject);
        subject.setText(selectedSubject.getSubjectDescription());
        subjectCodeInput.setText(selectedSubject.getSubjectCode());
        subjectDescriptionInput.setText(selectedSubject.getSubjectDescription());
        unitsInput.setText(String.valueOf(selectedSubject.getUnits()));
        
        if(Process.isDarkTheme()) {
            editSubjectDetailsPanel.setBackground(Process.DARK_COLOR);
            editSubjectDetailsHeader.setForeground(Process.LIGHT_COLOR);
            selectedSubjectLabel.setForeground(Process.LIGHT_COLOR);
            subject.setForeground(Process.LIGHT_COLOR);
            subjectCodeLabel.setForeground(Process.LIGHT_COLOR);
            subjectDescriptionLabel.setForeground(Process.LIGHT_COLOR);
            unitsLabel.setForeground(Process.LIGHT_COLOR);
        }
        else {
            editSubjectDetailsPanel.setBackground(Process.LIGHT_COLOR);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editSubjectDetailsPanel = new javax.swing.JPanel();
        editSubjectDetailsHeader = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        selectedSubjectLabel = new javax.swing.JLabel();
        subjectCodeLabel = new javax.swing.JLabel();
        subjectDescriptionLabel = new javax.swing.JLabel();
        unitsLabel = new javax.swing.JLabel();
        subjectCodeInput = new javax.swing.JTextField();
        subjectDescriptionInput = new javax.swing.JTextField();
        unitsInput = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Subject Details");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        editSubjectDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        editSubjectDetailsHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        editSubjectDetailsHeader.setText("Edit Subject Details");

        subject.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        selectedSubjectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectedSubjectLabel.setText("Selected Subject:");

        subjectCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectCodeLabel.setText("Subject code:");

        subjectDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectDescriptionLabel.setText("Subject description:");

        unitsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        unitsLabel.setText("Units:");

        subjectCodeInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        subjectDescriptionInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        unitsInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save_24px.png"))); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editSubjectDetailsPanelLayout = new javax.swing.GroupLayout(editSubjectDetailsPanel);
        editSubjectDetailsPanel.setLayout(editSubjectDetailsPanelLayout);
        editSubjectDetailsPanelLayout.setHorizontalGroup(
            editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSubjectDetailsPanelLayout.createSequentialGroup()
                .addGroup(editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editSubjectDetailsPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subjectDescriptionLabel)
                            .addComponent(subjectCodeLabel)
                            .addComponent(unitsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectCodeInput)
                            .addGroup(editSubjectDetailsPanelLayout.createSequentialGroup()
                                .addComponent(unitsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton))
                            .addComponent(subjectDescriptionInput)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editSubjectDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectedSubjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(editSubjectDetailsPanelLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(editSubjectDetailsHeader)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        editSubjectDetailsPanelLayout.setVerticalGroup(
            editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSubjectDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editSubjectDetailsHeader)
                .addGap(18, 18, 18)
                .addGroup(editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedSubjectLabel)
                    .addComponent(subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editSubjectDetailsPanelLayout.createSequentialGroup()
                        .addGroup(editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjectCodeLabel)
                            .addComponent(subjectCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjectDescriptionLabel)
                            .addComponent(subjectDescriptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editSubjectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitsLabel)
                            .addComponent(unitsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editSubjectDetailsPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editSubjectDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editSubjectDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(subjectCodeInput.getText().isEmpty() && subjectDescriptionInput.getText().isEmpty() && unitsInput.getText().isEmpty() && !Process.isNumber(unitsInput.getText())) {
            JOptionPane.showMessageDialog(null, "PLEASE INSERT THE FIELDS PROPERLY");
        }
        else {
            Process.subjects.get(EditSubjects.selectedSubject).setSubjectCode(subjectCodeInput.getText().trim());
            Process.subjects.get(EditSubjects.selectedSubject).setSubjectDescription(subjectDescriptionInput.getText().trim());
            Process.subjects.get(EditSubjects.selectedSubject).setUnits(Integer.parseInt(unitsInput.getText().trim()));
            Process.saveSubjectsToAFile();
            JOptionPane.showMessageDialog(null, "SUBJECT EDITED SUCCESSFULLY");
            this.dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSubjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditSubjectDetails().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editSubjectDetailsHeader;
    private javax.swing.JPanel editSubjectDetailsPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel selectedSubjectLabel;
    private javax.swing.JLabel subject;
    private javax.swing.JTextField subjectCodeInput;
    private javax.swing.JLabel subjectCodeLabel;
    private javax.swing.JTextField subjectDescriptionInput;
    private javax.swing.JLabel subjectDescriptionLabel;
    private javax.swing.JTextField unitsInput;
    private javax.swing.JLabel unitsLabel;
    // End of variables declaration//GEN-END:variables
}
