/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Process;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Subject;

/**
 *
 * @author 19
 */
public class AddSubjects extends javax.swing.JFrame {

    /**
     * Creates new form addSubjects
     */
    public AddSubjects() {
        initComponents();
        
        subjectsTextArea.setEditable(false);
        Process.subjects = new ArrayList<>();
        
        Process.populateSubjects();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/new_copy_24px.png")));
        if(Process.isDarkTheme()) {
            addStudentPanel.setBackground(Process.DARK_COLOR);
            addSubjectHeader.setForeground(Process.LIGHT_COLOR);
            subjectCodeLabel.setForeground(Process.LIGHT_COLOR);
            subjectDescriptionLabel.setForeground(Process.LIGHT_COLOR);
            subjectUnitsLabel.setForeground(Process.LIGHT_COLOR);
            listOfSubjectsLabel.setForeground(Process.LIGHT_COLOR);
            subjectsTextArea.setForeground(Process.DARK_COLOR);
        }
        else {
            addStudentPanel.setBackground(Process.LIGHT_COLOR);
        }
        
        Process.subjects.stream().forEach((subject) -> {
            subjectsTextArea.append(" " + subject.getSubjectDescription() + "\n");
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addStudentPanel = new javax.swing.JPanel();
        addSubjectHeader = new javax.swing.JLabel();
        subjectCodeInput = new javax.swing.JTextField();
        subjectDescriptionInput = new javax.swing.JTextField();
        subjectUnitsLabel = new javax.swing.JLabel();
        subjectCodeLabel = new javax.swing.JLabel();
        subjectDescriptionLabel = new javax.swing.JLabel();
        addSubjectButton = new javax.swing.JButton();
        listOfSubjectsLabel = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectsTextArea = new javax.swing.JTextArea();
        subjectUnitsInput = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Subjects");
        setBackground(new java.awt.Color(250, 250, 250));
        setResizable(false);

        addStudentPanel.setBackground(new java.awt.Color(250, 250, 250));

        addSubjectHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addSubjectHeader.setText("Add Subjects");

        subjectCodeInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        subjectDescriptionInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectDescriptionInput.setText(" ");

        subjectUnitsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectUnitsLabel.setText("Units:");

        subjectCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectCodeLabel.setText("Subject code:");

        subjectDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectDescriptionLabel.setText("Subject description:");

        addSubjectButton.setBackground(new java.awt.Color(255, 255, 255));
        addSubjectButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addSubjectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-48.png"))); // NOI18N
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });

        listOfSubjectsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listOfSubjectsLabel.setText("List of Subjects");

        doneButton.setBackground(new java.awt.Color(255, 255, 255));
        doneButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save_medium.png"))); // NOI18N
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        subjectsTextArea.setColumns(20);
        subjectsTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectsTextArea.setRows(5);
        jScrollPane1.setViewportView(subjectsTextArea);

        subjectUnitsInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectUnitsInput.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        javax.swing.GroupLayout addStudentPanelLayout = new javax.swing.GroupLayout(addStudentPanel);
        addStudentPanel.setLayout(addStudentPanelLayout);
        addStudentPanelLayout.setHorizontalGroup(
            addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStudentPanelLayout.createSequentialGroup()
                        .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectUnitsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subjectCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subjectDescriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addStudentPanelLayout.createSequentialGroup()
                                .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(addStudentPanelLayout.createSequentialGroup()
                                        .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(subjectCodeInput)
                                            .addComponent(subjectDescriptionInput, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(addStudentPanelLayout.createSequentialGroup()
                                        .addComponent(subjectUnitsInput)
                                        .addGap(246, 246, 246)))
                                .addComponent(jScrollPane1))
                            .addGroup(addStudentPanelLayout.createSequentialGroup()
                                .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStudentPanelLayout.createSequentialGroup()
                        .addGap(0, 368, Short.MAX_VALUE)
                        .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStudentPanelLayout.createSequentialGroup()
                                .addComponent(listOfSubjectsLabel)
                                .addGap(173, 173, 173))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStudentPanelLayout.createSequentialGroup()
                                .addComponent(addSubjectHeader)
                                .addGap(411, 411, 411))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStudentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addStudentPanelLayout.setVerticalGroup(
            addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSubjectHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listOfSubjectsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStudentPanelLayout.createSequentialGroup()
                        .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addStudentPanelLayout.createSequentialGroup()
                                .addComponent(subjectCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subjectDescriptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subjectDescriptionLabel)))
                            .addComponent(subjectCodeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjectUnitsLabel)
                            .addComponent(subjectUnitsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        if(subjectCodeInput.getText().isEmpty() || subjectDescriptionInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PLEASE INSERT THE FIELDS PROPERLY");
        }
        else {
            Process.exist = false;
            for (Subject subject : Process.subjects) {
                if (subject.getSubjectCode().equals(subjectCodeInput.getText().trim())) {
                    Process.exist = true;
                    break;
                }
            }
            if(Process.exist) {
                JOptionPane.showMessageDialog(null, "SUBJECT ALREADY EXIST"); 
            }
            else{
                Subject subject = new Subject(subjectCodeInput.getText().trim(), subjectDescriptionInput.getText().trim(), (int)subjectUnitsInput.getValue());
                Process.subjects.add(subject);
                subjectsTextArea.append(" " + subjectDescriptionInput.getText().trim() + "\n");
                JOptionPane.showMessageDialog(null, "SUBJECT ADDED");
            }
        }
    }//GEN-LAST:event_addSubjectButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        if (!Process.subjects.isEmpty()) {
            Process.saveSubjectsToAFile();
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(null, "PLEASE ADD A SUBJECT FIRST");
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddSubjects().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addStudentPanel;
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JLabel addSubjectHeader;
    private javax.swing.JButton doneButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listOfSubjectsLabel;
    private javax.swing.JTextField subjectCodeInput;
    private javax.swing.JLabel subjectCodeLabel;
    private javax.swing.JTextField subjectDescriptionInput;
    private javax.swing.JLabel subjectDescriptionLabel;
    private javax.swing.JSpinner subjectUnitsInput;
    private javax.swing.JLabel subjectUnitsLabel;
    private javax.swing.JTextArea subjectsTextArea;
    // End of variables declaration//GEN-END:variables
}
