/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import fileHandling.Process;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Course;
/**
 *
 * @author 19
 */
public class EditStudent extends javax.swing.JFrame {
    /**
     * Creates new form EditStudent
     */
    public EditStudent() {

        initComponents();
        
        Process.students = new ArrayList<>();
        Process.courses = new ArrayList<>();
        Process.populateStudents();
        Process.populateCourses();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/icons8-edit-profile-30.png")));
        if(!Process.students.isEmpty()) {
            firstNameInput.setText(Process.students.get(studentsComboBox.getSelectedIndex()).getFirstName());
            lastNameInput.setText(Process.students.get(studentsComboBox.getSelectedIndex()).getLastName());
            addressInput.setText(Process.students.get(studentsComboBox.getSelectedIndex()).getAddress());
            ageInput.setText(String.valueOf(Process.students.get(studentsComboBox.getSelectedIndex()).getAge()));
            studentIdInput.setText(Process.students.get(studentsComboBox.getSelectedIndex()).getStudentNumber());
        }
        
        if(Process.isDarkTheme()) {
            editOrRemoveStudentPanel.setBackground(Process.DARK_COLOR);
            selectAStudentLabel.setForeground(Process.LIGHT_COLOR);
            editOrRemoveStudentHeader.setForeground(Process.LIGHT_COLOR);
            firstNameLabel.setForeground(Process.LIGHT_COLOR);
            lastNameLabel.setForeground(Process.LIGHT_COLOR);
            ageLabel.setForeground(Process.LIGHT_COLOR);
            addressLabel.setForeground(Process.LIGHT_COLOR);
            studentIdLabel.setForeground(Process.LIGHT_COLOR);
            courseLabel.setForeground(Process.LIGHT_COLOR);
        }
        else {
            editOrRemoveStudentPanel.setBackground(Process.LIGHT_COLOR);
            selectAStudentLabel.setForeground(Process.DARK_COLOR);
            editOrRemoveStudentHeader.setForeground(Process.DARK_COLOR);
            firstNameLabel.setForeground(Process.DARK_COLOR);
            lastNameLabel.setForeground(Process.DARK_COLOR);
            ageLabel.setForeground(Process.DARK_COLOR);
            addressLabel.setForeground(Process.DARK_COLOR);
            studentIdLabel.setForeground(Process.DARK_COLOR);
            courseLabel.setForeground(Process.DARK_COLOR);
        }
        if(Process.getStudents().length != 0 && Process.getCourses().length != 0) {
            studentsComboBox.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 18));
            studentsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Process.getStudents()));
            
            coursesComboBox.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 18));
            coursesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Process.getCourses()));
        }
        else {
            studentsComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            studentsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"NO STUDENTS AVAILABLE"}));
            
            coursesComboBox.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 18));
            coursesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"NO COURSES AVAILABLE"}));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editOrRemoveStudentPanel = new javax.swing.JPanel();
        editOrRemoveStudentHeader = new javax.swing.JLabel();
        selectAStudentLabel = new javax.swing.JLabel();
        studentsComboBox = new javax.swing.JComboBox<>();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        ageInput = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        studentIdLabel = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        courseLabel = new javax.swing.JLabel();
        coursesComboBox = new javax.swing.JComboBox<>();
        addressInput = new javax.swing.JTextField();
        studentIdInput = new javax.swing.JTextField();
        saveStudentButton = new javax.swing.JButton();
        removeStudentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit or Remove Student");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        editOrRemoveStudentHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        editOrRemoveStudentHeader.setText("Edit or Remove Student");

        selectAStudentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectAStudentLabel.setText("Select a Student:");

        studentsComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studentsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student 1", "Student 2", "Student 3", "Student 4" }));
        studentsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsComboBoxActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name:");

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name:");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ageLabel.setText("Age:");

        ageInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressLabel.setText("Address:");

        firstNameInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        studentIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studentIdLabel.setText("Student ID:");

        lastNameInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameInputActionPerformed(evt);
            }
        });

        courseLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseLabel.setText("Course:");

        coursesComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        coursesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3", "Course 4" }));

        addressInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        studentIdInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        saveStudentButton.setBackground(new java.awt.Color(255, 255, 255));
        saveStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save_24px.png"))); // NOI18N
        saveStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStudentButtonActionPerformed(evt);
            }
        });

        removeStudentButton.setBackground(new java.awt.Color(255, 255, 255));
        removeStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Remove_24px.png"))); // NOI18N
        removeStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editOrRemoveStudentPanelLayout = new javax.swing.GroupLayout(editOrRemoveStudentPanel);
        editOrRemoveStudentPanel.setLayout(editOrRemoveStudentPanelLayout);
        editOrRemoveStudentPanelLayout.setHorizontalGroup(
            editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editOrRemoveStudentPanelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(editOrRemoveStudentHeader)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editOrRemoveStudentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editOrRemoveStudentPanelLayout.createSequentialGroup()
                        .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(courseLabel)
                            .addComponent(studentIdLabel)
                            .addComponent(addressLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(selectAStudentLabel)
                            .addComponent(ageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentsComboBox, 0, 485, Short.MAX_VALUE)
                            .addComponent(firstNameInput)
                            .addComponent(lastNameInput)
                            .addComponent(addressInput)
                            .addComponent(studentIdInput)
                            .addComponent(coursesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ageInput))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editOrRemoveStudentPanelLayout.createSequentialGroup()
                        .addComponent(removeStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        editOrRemoveStudentPanelLayout.setVerticalGroup(
            editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editOrRemoveStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editOrRemoveStudentHeader)
                .addGap(18, 18, 18)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAStudentLabel)
                    .addComponent(studentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdLabel)
                    .addComponent(studentIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLabel)
                    .addComponent(coursesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(editOrRemoveStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(saveStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editOrRemoveStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editOrRemoveStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameInputActionPerformed

    private void studentsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsComboBoxActionPerformed
        firstNameInput.setText(Process.students.get(studentsComboBox.getSelectedIndex()).getFirstName());
        lastNameInput.setText(Process.students.get(studentsComboBox.getSelectedIndex()).getLastName());
        ageInput.setText(String.valueOf(Process.students.get(studentsComboBox.getSelectedIndex()).getAge()));
        addressInput.setText(Process.students.get(studentsComboBox.getSelectedIndex()).getAddress());
        studentIdInput.setText(Process.students.get(studentsComboBox.getSelectedIndex()).getStudentNumber());
        
        Course course = Process.courses.get(studentsComboBox.getSelectedIndex());
        int courseIndex = 0;
        for (int i = 0; i < Process.courses.size(); i++) {
            if(Process.courses.get(i).equals(course)) {
               courseIndex = i;
               break;
            }
        }
        coursesComboBox.setSelectedIndex(courseIndex);
    }//GEN-LAST:event_studentsComboBoxActionPerformed

    private void removeStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudentButtonActionPerformed
        Process.students.remove(studentsComboBox.getSelectedIndex());
        Process.saveStudentsToAFile();
        JOptionPane.showMessageDialog(null, "STUDENT REMVED SUCCESSFULLY");
        this.dispose();
    }//GEN-LAST:event_removeStudentButtonActionPerformed

    private void saveStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStudentButtonActionPerformed
        
        if(firstNameInput.getText().isEmpty() && 
           lastNameInput.getText().isEmpty() && 
           ageInput.getText().isEmpty() &&
           addressInput.getText().isEmpty() &&
           !Process.isNumber(studentIdInput.getText().trim())) {
            JOptionPane.showMessageDialog(null, "PLEASE INSERT THE FIELDS PROPERLY");
        }
        else {
            Process.students.get(studentsComboBox.getSelectedIndex()).setFirstName(firstNameInput.getText().trim());
            Process.students.get(studentsComboBox.getSelectedIndex()).setLastName(lastNameInput.getText().trim());
            Process.students.get(studentsComboBox.getSelectedIndex()).setAge(Byte.parseByte(ageInput.getText().trim()));
            Process.students.get(studentsComboBox.getSelectedIndex()).setAddress(addressInput.getText().trim());
            Process.students.get(studentsComboBox.getSelectedIndex()).setStudentNumber(studentIdInput.getText().trim());
            Process.students.get(studentsComboBox.getSelectedIndex()).setCourse(Process.courses.get(coursesComboBox.getSelectedIndex()));
            Process.saveStudentsToAFile();
            JOptionPane.showMessageDialog(null, "STUDENT SAVED SUCCESSFULLY");
            this.dispose();
        }
    }//GEN-LAST:event_saveStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditStudent().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField ageInput;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JComboBox<String> coursesComboBox;
    private javax.swing.JLabel editOrRemoveStudentHeader;
    private javax.swing.JPanel editOrRemoveStudentPanel;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton removeStudentButton;
    private javax.swing.JButton saveStudentButton;
    private javax.swing.JLabel selectAStudentLabel;
    private javax.swing.JTextField studentIdInput;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JComboBox<String> studentsComboBox;
    // End of variables declaration//GEN-END:variables
}
