package view;

import controller.Process;
import java.awt.Toolkit;

/*
 * To change this license header, ch oose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 19
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form GUI
     */
    public Menu() {
        Process.populateTheme();
        Process.setTheme(Process.isDarkTheme());
        
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/ico.png")));
        if(Process.isDarkTheme()) {
            menuPanel.setBackground(Process.DARK_COLOR);
            menuBar.setBackground(Process.DARK_COLOR);
            toggleDarkModeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/light_mode_small.png")));
            
        }
        else {
            menuPanel.setBackground(Process.LIGHT_COLOR);
            menuBar.setBackground(Process.LIGHT_COLOR);
            toggleDarkModeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dark_mode_small.png")));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        toggleDarkModeMenu = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        addMenu = new javax.swing.JMenu();
        addSubjectsMenuItem = new javax.swing.JMenuItem();
        addCourseMenuItem = new javax.swing.JMenuItem();
        addStudentMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        edutSubjectsMenuItem = new javax.swing.JMenuItem();
        edutCourseMenuItem = new javax.swing.JMenuItem();
        editStudentMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        menuPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        homeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/students.png"))); // NOI18N
        homeIcon.setLabelFor(this);
        homeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeIcon.setFocusable(false);
        homeIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeIcon.setNextFocusableComponent(this);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        homeIcon.getAccessibleContext().setAccessibleDescription("");

        menuBar.setBackground(new java.awt.Color(255, 255, 255));

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/file_small.png"))); // NOI18N
        if(Process.isDarkTheme()) {
            toggleDarkModeMenu.setText("Light theme");
            toggleDarkModeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/light_mode_small.png"))); // NOI18N
        }
        else {
            toggleDarkModeMenu.setText("Dark theme");
            toggleDarkModeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dark_mode_small.png"))); // NOI18N
        }
        toggleDarkModeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleDarkModeMenuActionPerformed(evt);
            }
        });
        fileMenu.add(toggleDarkModeMenu);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_window_24px.png"))); // NOI18N
        exitMenuItem.setText("exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        addMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_small.png"))); // NOI18N

        addSubjectsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_copy_24px.png"))); // NOI18N
        addSubjectsMenuItem.setText("Add Subjects");
        addSubjectsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectsMenuItemActionPerformed(evt);
            }
        });
        addMenu.add(addSubjectsMenuItem);

        addCourseMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_course_small.png"))); // NOI18N
        addCourseMenuItem.setText("Add Course");
        addCourseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseMenuItemActionPerformed(evt);
            }
        });
        addMenu.add(addCourseMenuItem);

        addStudentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_student_small.png"))); // NOI18N
        addStudentMenuItem.setText("Add Student");
        addStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentMenuItemActionPerformed(evt);
            }
        });
        addMenu.add(addStudentMenuItem);

        menuBar.add(addMenu);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_small.png"))); // NOI18N

        edutSubjectsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_subject_small.png"))); // NOI18N
        edutSubjectsMenuItem.setText("Edit Subjects");
        edutSubjectsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edutSubjectsMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(edutSubjectsMenuItem);

        edutCourseMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_course_small.png"))); // NOI18N
        edutCourseMenuItem.setText("Edit Course");
        edutCourseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edutCourseMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(edutCourseMenuItem);

        editStudentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-profile-30.png"))); // NOI18N
        editStudentMenuItem.setText("Edit Student");
        editStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(editStudentMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        Process.saveTheme();
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addSubjectsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectsMenuItemActionPerformed
        new AddSubjects().setVisible(true);
    }//GEN-LAST:event_addSubjectsMenuItemActionPerformed

    private void addCourseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseMenuItemActionPerformed
        new AddCourse().setVisible(true);
        Process.listOfAddedSubjects.clear();
    }//GEN-LAST:event_addCourseMenuItemActionPerformed

    private void addStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentMenuItemActionPerformed
        new AddStudent().setVisible(true);
    }//GEN-LAST:event_addStudentMenuItemActionPerformed

    private void toggleDarkModeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleDarkModeMenuActionPerformed
        if(Process.isDarkTheme()) {
            toggleDarkModeMenu.setText("Light Theme");
            toggleDarkModeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/light_mode_small.png")));
            menuPanel.setBackground(Process.LIGHT_COLOR);
            menuBar.setBackground(Process.LIGHT_COLOR);
            setBackground(Process.LIGHT_COLOR);
            Process.setTheme(false);
            if(!Process.isDarkTheme()) {
                toggleDarkModeMenu.setText("Dark Theme");
                toggleDarkModeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dark_mode_small.png")));
            }
        }
        else {
            if(Process.isDarkTheme()) {
                toggleDarkModeMenu.setText("Dark Theme");
                toggleDarkModeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dark_mode_small.png")));
            }
            else {
                toggleDarkModeMenu.setText("Light Theme");
                toggleDarkModeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/light_mode_small.png")));
            }
            menuPanel.setBackground(Process.DARK_COLOR);
            menuBar.setBackground(Process.DARK_COLOR);
            setBackground(Process.DARK_COLOR);
            Process.setTheme(true);
        }

    }//GEN-LAST:event_toggleDarkModeMenuActionPerformed

    private void edutSubjectsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edutSubjectsMenuItemActionPerformed
        new EditSubjects().setVisible(true);
    }//GEN-LAST:event_edutSubjectsMenuItemActionPerformed

    private void edutCourseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edutCourseMenuItemActionPerformed
        new EditCourses().setVisible(true);
    }//GEN-LAST:event_edutCourseMenuItemActionPerformed

    private void editStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editStudentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCourseMenuItem;
    private javax.swing.JMenu addMenu;
    private javax.swing.JMenuItem addStudentMenuItem;
    private javax.swing.JMenuItem addSubjectsMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem editStudentMenuItem;
    private javax.swing.JMenuItem edutCourseMenuItem;
    private javax.swing.JMenuItem edutSubjectsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JMenuItem toggleDarkModeMenu;
    // End of variables declaration//GEN-END:variables

}
