/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.editCourseDetails;

import javax.swing.JOptionPane;
import controller.Process;
import java.awt.Toolkit;
import java.util.ArrayList;
import view.EditCourses;
import model.Course;
import model.Subject;

/**
 *
 * @author 19
 */
public class EditCourseDetails extends javax.swing.JFrame {
    private static Course selectedCourse;
    private static ArrayList<Subject> courseSubjects = new ArrayList<>();
    
    /**
     * Creates new form EditCourseDetails
     */
    public EditCourseDetails() {
        JOptionPane.showMessageDialog(null, "ONLY CLICK THE SAVE ICON WHEN YOU ARE DONE EDITING THE COURSE");
        initComponents();
        
        Process.subjects = new ArrayList<>();
        Process.listOfCourseSubjects = new ArrayList<>();
        courseSubjectsList.setEditable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/add_course_small.png")));
        
        selectedCourse = Process.courses.get(EditCourses.selectedCourse);
        course.setText(selectedCourse.getCourseDescription());
        courseCodeInput.setText(selectedCourse.getCourseCode());
        courseDescriptionInput.setText(selectedCourse.getCourseDescription());
        
        if(Process.isDarkTheme()) {
            editCourseDetailsPanel.setBackground(Process.DARK_COLOR);
            editCourseDetailsHeader.setForeground(Process.LIGHT_COLOR);
            selectedCourseLabel.setForeground(Process.LIGHT_COLOR);
            course.setForeground(Process.LIGHT_COLOR);
            courseCodeLabel.setForeground(Process.LIGHT_COLOR);
            courseDescriptionLabel.setForeground(Process.LIGHT_COLOR);
            subjectsLabel.setForeground(Process.LIGHT_COLOR);
            listOfCourseSubjectsLabel.setForeground(Process.LIGHT_COLOR);
        }
        else {
            editCourseDetailsPanel.setBackground(Process.LIGHT_COLOR);
        }

        getCourseSubjects();
        subjectsComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18));
        subjectsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Process.getSubjects()));
    }
    
    private void getCourseSubjects() {
        for(int i = 0; i < selectedCourse.getSubjects().size(); i++) {
            courseSubjectsList.append(" " + selectedCourse.getSubjects().get(i).getSubjectDescription() + "\n");
            Process.listOfCourseSubjects.add(selectedCourse.getSubjects().get(i).getSubjectCode());
            courseSubjects.add(selectedCourse.getSubjects().get(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editCourseDetailsPanel = new javax.swing.JPanel();
        editCourseDetailsHeader = new javax.swing.JLabel();
        selectedCourseLabel = new javax.swing.JLabel();
        courseCodeLabel = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        courseDescriptionLabel = new javax.swing.JLabel();
        courseCodeInput = new javax.swing.JTextField();
        courseDescriptionInput = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        courseSubjectsList = new javax.swing.JTextArea();
        listOfCourseSubjectsLabel = new javax.swing.JLabel();
        subjectsLabel = new javax.swing.JLabel();
        subjectsComboBox = new javax.swing.JComboBox();
        addSubjectButton = new javax.swing.JButton();
        removeSubjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Course Details");
        setResizable(false);

        editCourseDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        editCourseDetailsHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        editCourseDetailsHeader.setText("Edit Course Details");

        selectedCourseLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectedCourseLabel.setText("Selected Course:");

        courseCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseCodeLabel.setText("Course code:");

        course.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        courseDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseDescriptionLabel.setText("Course description:");

        courseCodeInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseCodeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCodeInputActionPerformed(evt);
            }
        });

        courseDescriptionInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save_24px.png"))); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        courseSubjectsList.setColumns(20);
        courseSubjectsList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseSubjectsList.setRows(5);
        scrollPanel.setViewportView(courseSubjectsList);

        listOfCourseSubjectsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listOfCourseSubjectsLabel.setText("List of Course Subjects");

        subjectsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectsLabel.setText("Subjects:");

        subjectsComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subjectsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        subjectsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectsComboBoxActionPerformed(evt);
            }
        });

        addSubjectButton.setBackground(new java.awt.Color(255, 255, 255));
        addSubjectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-48.png"))); // NOI18N
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });

        removeSubjectButton.setBackground(new java.awt.Color(255, 255, 255));
        removeSubjectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remove-32.png"))); // NOI18N
        removeSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSubjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editCourseDetailsPanelLayout = new javax.swing.GroupLayout(editCourseDetailsPanel);
        editCourseDetailsPanel.setLayout(editCourseDetailsPanelLayout);
        editCourseDetailsPanelLayout.setHorizontalGroup(
            editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCourseDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editCourseDetailsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editCourseDetailsPanelLayout.createSequentialGroup()
                        .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(courseDescriptionLabel)
                            .addComponent(courseCodeLabel)
                            .addComponent(subjectsLabel)
                            .addComponent(selectedCourseLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editCourseDetailsPanelLayout.createSequentialGroup()
                                .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editCourseDetailsPanelLayout.createSequentialGroup()
                                        .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(courseCodeInput)
                                            .addComponent(courseDescriptionInput)
                                            .addComponent(subjectsComboBox, 0, 400, Short.MAX_VALUE))
                                        .addGap(52, 52, 52))
                                    .addGroup(editCourseDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editCourseDetailsPanelLayout.createSequentialGroup()
                                .addComponent(course)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(listOfCourseSubjectsLabel)
                                .addGap(112, 112, 112)))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCourseDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editCourseDetailsHeader)
                .addGap(385, 385, 385))
        );
        editCourseDetailsPanelLayout.setVerticalGroup(
            editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCourseDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editCourseDetailsHeader)
                .addGap(34, 34, 34)
                .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listOfCourseSubjectsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectedCourseLabel)
                        .addComponent(course)))
                .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editCourseDetailsPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseCodeLabel)
                            .addComponent(courseCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseDescriptionLabel)
                            .addComponent(courseDescriptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjectsLabel)
                            .addComponent(subjectsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(editCourseDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeSubjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94))
                    .addGroup(editCourseDetailsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollPanel)
                        .addGap(18, 18, 18)))
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editCourseDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editCourseDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(courseCodeInput.getText().isEmpty() && courseDescriptionInput.getText().isEmpty() && courseSubjects.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PLEASE INSERT THE FIELDS PROPERLY");
        }
        else {
            for (Subject subject : courseSubjects) {
                Process.courses.get(EditCourses.selectedCourse).setCourseCode(subject.getSubjectCode());
                Process.courses.get(EditCourses.selectedCourse).setCourseDescription(subject.getSubjectDescription());
            }
            Process.saveCoursesToAFile();
            JOptionPane.showMessageDialog(null, "COURSE EDITED SUCCESSFULLY");
            this.dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void courseCodeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCodeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseCodeInputActionPerformed

    private void subjectsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectsComboBoxActionPerformed

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        Subject subject = new Subject();
        
        if(courseCodeInput.getText().trim().isEmpty() && courseDescriptionInput.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PLEASE INSERT THE FIELDS PROPERLY");
        }
        else {
            subject.setSubjectCode(Process.subjects.get(subjectsComboBox.getSelectedIndex()).getSubjectCode());
            subject.setSubjectDescription(Process.subjects.get(subjectsComboBox.getSelectedIndex()).getSubjectDescription());
            subject.setUnits(Process.subjects.get(subjectsComboBox.getSelectedIndex()).getUnits());
            
            Process.exist = false;
            
            for(String addedSubject : Process.listOfCourseSubjects) {
                if (addedSubject.contains(subject.getSubjectCode())) {
                    Process.exist = true;
                    break;
                }
            }
            
            if(Process.exist) {
                JOptionPane.showMessageDialog(null, "SUBJECT ALREADY ADDED");
            }
            else {
                courseSubjectsList.append(" " + subject.getSubjectDescription() + "\n");
                JOptionPane.showMessageDialog(null, "SUBJECT ADDED");
                Process.listOfCourseSubjects.add(subject.getSubjectCode());
            }
        }
    }//GEN-LAST:event_addSubjectButtonActionPerformed

    private void removeSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSubjectButtonActionPerformed
        getCourseSubjects();
    }//GEN-LAST:event_removeSubjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditCourseDetails().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JLabel course;
    private javax.swing.JTextField courseCodeInput;
    private javax.swing.JLabel courseCodeLabel;
    private javax.swing.JTextField courseDescriptionInput;
    private javax.swing.JLabel courseDescriptionLabel;
    private javax.swing.JTextArea courseSubjectsList;
    private javax.swing.JLabel editCourseDetailsHeader;
    private javax.swing.JPanel editCourseDetailsPanel;
    private javax.swing.JLabel listOfCourseSubjectsLabel;
    private javax.swing.JButton removeSubjectButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel selectedCourseLabel;
    private javax.swing.JComboBox subjectsComboBox;
    private javax.swing.JLabel subjectsLabel;
    // End of variables declaration//GEN-END:variables
}
